server:
  port: 8090

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v0
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # 访问频次限制
    limit-count: 3
    # 白名单，不做频次拦截【微信的openai】oxfA9w8-23yvwTmo2ombz0E4zJv4
    white-list: user004

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGLM SDK Config
chatglm:
  sdk:
    config:
      api-host: https://open.bigmodel.cn/
      api-key: d847050042570e7136f926a7d3cc3e83.UMIVEHtoforykzFU

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml